Document: lbtt
Title: Debian lbtt Manual
Author: <insert document author here>
Abstract: This manual describes what lbtt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lbtt/lbtt.sgml.gz

Format: postscript
Files: /usr/share/doc/lbtt/lbtt.ps.gz

Format: text
Files: /usr/share/doc/lbtt/lbtt.text.gz

Format: HTML
Index: /usr/share/doc/lbtt/html/index.html
Files: /usr/share/doc/lbtt/html/*.html
